import { config } from "dotenv";
config();
export const {
  CORS_ORIGIN,
  PORT,
  STATION_ACCESS_TOKEN_SECRET,
  STATION_REFRESH_TOKEN_SECRET,
  USER_ACCESS_TOKEN_SECRET,
  MONGODB_URI,
  ACCESS_TOKEN_EXPIRY,
  REFRESH_TOKEN_EXPIRY,
  USER_REFRESH_TOKEN_SECRET,
  CLOUD_NAME,
  API_KEY,
  API_SECRET,
} = process.env;
